repos:
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
        - id: black
          files: src/.*

    - repo: https://github.com/PyCQA/pydocstyle
      rev: 6.1.1
      hooks:
        - id: pydocstyle
          args:  ['--convention', 'pep257', '--add-ignore', 'D1']
          files: .*

    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            language_version: python3
            args: ["--select", "C,E,F,W", "--ignore", "E501,W503,F401"]
            files: .*

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
            language_version: python3
            args: ["--profile", "black", "--project", "applitoolsify", "--project", "src"]
            entry: isort
            files: .*
            additional_dependencies: [toml]

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
            files: .*
            exclude: setup.cfg|python/tests/.*
          - id: end-of-file-fixer
            files: .*
            exclude: tests/.*
          - id: debug-statements
            files: .*
          - id: check-case-conflict
            files: src/.*
          - id: check-byte-order-marker
            files: .*
            exclude: python/tests/.*
          - id: mixed-line-ending
            files: .*
            exclude: tests/.*
            args:
                - --fix=lf
