name: Android injection tests
run-name: ${{ github.actor }} is performing UT for injection
on: [push]
jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Set up Python
        if: ${{ !failure() }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Java 11 for apk patcher
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/checkout@v2
        if: ${{ !failure() }}

      - name: Install dependencies
        if: ${{ !failure() }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest==6.2.5 pytest-xdist==2.5.0
      
      - name: Make standalone (win)
        if: ${{ matrix.os == 'windows' }}
        run: |
          echo "Making bundle"
          ./bundle.bat
        
      - name: Make standalone (mac)
        if: ${{ matrix.os == 'macOS' }}
        run: |
          echo "Making bundle"
          ./bundle.sh
