name: iOS Deployment
run-name: ${{ github.actor }} is performing iOS deployment
on: [push]
jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest, ARM64]
      fail-fast: false
    steps:
      - name: Set up Python
        if: ${{ matrix.os != 'ARM64' && !failure() }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Java 11 for apk patcher
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/checkout@v2
        if: ${{ !failure() }}

      - name: Install dependencies
        if: ${{ !failure() && matrix.os == 'ARM64'}}
        run: |
          pip3 install pytest==6.2.5 pytest-xdist==2.5.0 pyinstaller

      - name: Install dependencies
        if: ${{ matrix.os != 'ARM64'}}
        run: |
          pip install pytest=6.2.5 pytest-xdist==2.5.0 pyinstaller
      
      - name: Make standalone (win)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "Making bundle"
          cd src
          bundle.bat
        
      - name: Make standalone (mac)
        if: ${{ matrix.os == 'macOS-latest' }}
        run: |
          echo "Making bundle"
          cd src
          ./bundle.sh
      
      - name: Make standalone (mac m1)
        if: ${{ matrix.os == 'ARM64' }}
        run: |
          echo "Making bundle"
          cd src
          ./bundle.sh
      
      - name: Make standalone (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "Making bundle"
          cd src
          ./bundle.sh
