name: Test that applitoolsify works on multiple platorms and Python versions
on: push
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["2.7", "3.6", "3.10"]
    steps:
      - uses: actions/checkout@v2
        if: ${{ !failure() }}
      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ !failure() }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: ${{ !failure() }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        if: ${{ !failure() }}
        run: pytest