name: Test that applitoolsify works on multiple platorms and Python versions
on: push
jobs:
  run-tests-on-lin-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.6", "3.10"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ !failure() }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2
        if: ${{ !failure() }}

      - name: Install dependencies
        if: ${{ !failure() }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        if: ${{ !failure() }}
        run: pytest

  run-tests-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.10"]
    steps:
      - name: Set the LongPathsEnabled on Windows
        run: 'New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force'

      - name: Set up Python ${{ matrix.python-version }}
        if: ${{ !failure() }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2
        if: ${{ !failure() }}

      - name: Install dependencies
        if: ${{ !failure() }}
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        if: ${{ !failure() }}
        run: pytest